[package]
name = "service_sqs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = {workspace = true}
aws-sdk-sqs = { workspace = true }

model = { path = "../model" }
service = { path = "../service" }
