[package]
name = "test_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {workspace = true}
aws_lambda_events = {workspace = true}
aws-sdk-sqs = {workspace = true, features = ["test-util"]}
aws-smithy-mocks = {workspace = true}

model = { path = "../model" }