[package]
name = "lambda-workflow"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { version = "0.16.0", default-features = false, features = ["sqs"] }
aws-sdk-sqs = "1.72.0"
aws-types = "1.3.7"

serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"

lambda_runtime = "0.14.1"
tokio = { version = "1", features = ["macros"] }
