[package]
name = "state_in_memory"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
async-trait = {workspace = true}

state = {path = "../state"}
model = {path = "../model"}
