[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }

aws-sdk-sqs = { workspace = true }
aws-types = { workspace = true }
serde_json = { workspace = true }

model = { path = "../model" }
